FrmBlog/Controllers/AraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FrmBlog.Filters;
using FrmBlog.Repositorys;
using FrmBlog.Models;
using FrmBlog.ViewData;
namespace FrmBlog.Controllers
{
    public class AraController : BaseController
    {
        //
        // GET: /Ara/

        public ActionResult Index(int?page,string q)
        {
            RepositoryQuestion _repQues = new RepositoryQuestion("",DbType.SqLite);
            RepositorySetting _repoSet = new RepositorySetting("",DbType.SqLite);
            RepositoryTag _repoTag = new RepositoryTag("",DbType.SqLite);
            int totalCount;
            if(!string.IsNullOrEmpty(q))
                q = q.Replace("'", "%t%");
            FrmViewData frm = new FrmViewData();
            frm.Questions = _repQues.GetListQueryByDate(q,PagerCount(), page ?? 1, out totalCount);
            PaginatedList pager = new PaginatedList((page ?? 1), PagerCount(), totalCount);
            ViewBag.SiteName = _repoSet[SettingKey.SiteName];
            ViewData["queryData"] = q;
            return View(frm.WithPaging(pager).WithTags(_repoTag.GetAll()));
        }

    }
}

FrmBlog/Controllers/AuthController.cs
//-----------------------------------------------------------------------
// <copyright file="AuthController.cs" company="Andrew Arnott">
//     Copyright (c) Andrew Arnott. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace MvcRelyingParty.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using DotNetOpenAuth.Messaging;
    using DotNetOpenAuth.OpenId;
    using DotNetOpenAuth.OpenId.RelyingParty;
    using System.Web.Security;
    using DotNetOpenAuth.OpenId.Extensions.SimpleRegistration;
    using FrmBlog.Repositorys;
    using FrmBlog.Controllers;
    using System.Threading;
    public class AuthController:BaseController //: BaseController
    {

        /// <summary>
        /// Gets the OpenID relying party to use for logging users in.
        /// </summary>
        public IOpenIdRelyingParty RelyingParty = new OpenIdRelyingPartyService();

        private Uri PrivacyPolicyUrl
        {
            get
            {
                return Url.ActionFull("PrivacyPolicy", "Home");
            }
        }

        /// <summary>
        /// Performs discovery on a given identifier.
        /// </summary>
        /// <param name="identifier">The identifier on which to perform discovery.</param>
        /// <returns>The JSON result of discovery.</returns>
        public ActionResult Discover(string identifier)
        {
            if (!this.Request.IsAjaxRequest())
            {
                throw new InvalidOperationException();
            }

            return RelyingParty.AjaxDiscovery(
                identifier,
                Realm.AutoDetect,
                Url.ActionFull("PopUpReturnTo"),
                this.PrivacyPolicyUrl);
        }

        /// <summary>
        /// Prepares a web page to help the user supply his login information.
        /// </summary>
        /// <returns>The action result.</returns>
        public ActionResult LogOn()
        {
            return View();
        }

        /// <summary>
        /// Prepares a web page to help the user supply his login information.
        /// </summary>
        /// <returns>The action result.</returns>
        public ActionResult LogOnPopUp()
        {
            return View();
        }

        /// <summary>
        /// Handles the positive assertion that comes from Providers to Javascript running in the browser.
        /// </summary>
        /// <returns>The action result.</returns>
        /// <remarks>
        /// This method instructs ASP.NET MVC to <i>not</i> validate input
        /// because some OpenID positive assertions messages otherwise look like
        /// hack attempts and result in errors when validation is turned on.
        /// </remarks>
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post), ValidateInput(false)]
        public ActionResult PopUpReturnTo()
        {
            return RelyingParty.ProcessAjaxOpenIdResponse();
        }

        /// <summary>
        /// Handles the positive assertion that comes from Providers.
        /// </summary>
        /// <param name="openid_openidAuthData">The positive assertion obtained via AJAX.</param>
        /// <returns>The action result.</returns>
        /// <remarks>
        /// This method instructs ASP.NET MVC to <i>not</i> validate input
        /// because some OpenID positive assertions messages otherwise look like
        /// hack attempts and result in errors when validation is turned on.
        /// </remarks>
        [HttpPost, ValidateInput(false)]
        public ActionResult LogOnPostAssertion(string openid_openidAuthData)
        {
            IAuthenticationResponse response;
            if (!string.IsNullOrEmpty(openid_openidAuthData))
            {
                var auth = new Uri(openid_openidAuthData);
                var headers = new WebHeaderCollection();
                foreach (string header in Request.Headers)
                {
                    headers[header] = Request.Headers[header];
                }

                // Always say it's a GET since the payload is all in the URL, even the large ones.
                HttpRequestInfo clientResponseInfo = new HttpRequestInfo("GET", auth, auth.PathAndQuery, headers, null);
                response = RelyingParty.GetResponse(clientResponseInfo);
            }
            else
            {
                response = RelyingParty.GetResponse();
            }
            if (response != null)
            {
                switch (response.Status)
                {
                    case AuthenticationStatus.Authenticated:
                        string alias = response.FriendlyIdentifierForDisplay;
                        var sreg = response.GetExtension<ClaimsResponse>();
                        if (sreg != null && sreg.MailAddress != null)
                        {
                            RepositoryUser userRepo = new RepositoryUser("", DbType.SqLite);
                            if (!userRepo.IsRecordUser(sreg.MailAddress.Address.Trim()))
                            {
                                FrmBlog.Models.User user = new FrmBlog.Models.User();
                                user.DisplayName = sreg.MailAddress.DisplayName;
                                user.Email = sreg.MailAddress.Address;
                                user.RecordDate = DateTime.Now;
                                user.RoleId = FrmBlog.Models.Role.Member.RoleId;
                                user.Name = sreg.MailAddress.User;
                                user.PicturePath = new FrmBlog.Avatar.Avatar().GetRandomAvatar();
                                userRepo.Insert(user);
                               
                            }
                            else {
                                var user = userRepo.GetUserByEmail(sreg.MailAddress.Address);
                              
                            }
                          //FormsAuthenticationTicket authTicket = new
                          //FormsAuthenticationTicket(1, //version
                          //response.ClaimedIdentifier, // user name
                          //DateTime.Now,             //creation
                          //DateTime.Now.AddMonths(12), //Expiration
                          //true, //Persistent
                          //sreg.MailAddress.Address);

                          //  string encTicket = FormsAuthentication.Encrypt(authTicket);

                          //  this.Response.Cookies.Add(new HttpCookie(FormsAuthentication.FormsCookieName, encTicket));
                          //  alias = sreg.MailAddress.User;
                            FormsAuthentication.SetAuthCookie(sreg.MailAddress.Address, true);
                        }
                        //if (sreg != null && !string.IsNullOrEmpty(sreg.FullName))
                        //{
                        //    alias = sreg.FullName;
                        //}

                        //FormsAuthenticationTicket authTicket = new
                        //    FormsAuthenticationTicket(1, //version
                        //    response.ClaimedIdentifier, // user name
                        //    DateTime.Now,             //creation
                        //    DateTime.Now.AddDays(365), //Expiration
                        //    false, //Persistent
                        //    alias);

                        //string encTicket = FormsAuthentication.Encrypt(authTicket);

                        //this.Response.Cookies.Add(new HttpCookie(FormsAuthentication.FormsCookieName, encTicket));

                       
                        string returnUrl = Request.Form["returnUrl"];
                        if (!String.IsNullOrEmpty(returnUrl))
                        {
                            return Redirect(returnUrl);
                        }
                        else
                        {
                            return RedirectToAction("Index", "Home");
                        }
                    case AuthenticationStatus.Canceled:
                        ModelState.AddModelError("OpenID", "It looks like you canceled login at your OpenID Provider.");
                        break;
                    case AuthenticationStatus.Failed:
                        ModelState.AddModelError("OpenID", response.Exception.Message);
                        break;
                }
            }

            // If we're to this point, login didn't complete successfully.
            // Show the LogOn view again to show the user any errors and
            // give another chance to complete login.
            return View("LogOn");
        }
    }
}

FrmBlog/Views/Shared/Editor.cshtml
<script src="../../../../Scripts/tiny_mce/tiny_mce.js" type="text/javascript"></script>
   <script type="text/javascript">
       tinyMCE.init({
           // General options
          //forced_root_block: "true",
           //force_br_newlines: "false",
           //force_p_newlines: "true",
           mode: "textareas",
           theme: "advanced",
           plugins: "style,layer,table,save,advhr,advimage,advlink,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist",

           // Theme options
           theme_advanced_buttons1: "link,image,code,blockquote,bullist,numlist,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect",
           theme_advanced_buttons2: "fontsizeselect",
           theme_advanced_buttons3: "",
           theme_advanced_toolbar_location: "top",
           theme_advanced_toolbar_align: "left",
           theme_advanced_statusbar_location: "bottom",
           theme_advanced_resizing: true,
           theme_advanced_path: false,
           // Example content CSS (should be your site CSS)
           content_css: "css/content.css",

           // Drop lists for link/image/media/template dialogs
           template_external_list_url: "lists/template_list.js",
           external_link_list_url: "lists/link_list.js",
           external_image_list_url: "lists/image_list.js",
           media_external_list_url: "lists/media_list.js",

           // Style formats
           style_formats: [
			{ title: 'Bold text', inline: 'b' },
			{ title: 'Red text', inline: 'span', styles: { color: '#ff0000'} },
			{ title: 'Red header', block: 'h1', styles: { color: '#ff0000'} },
			{ title: 'Example 1', inline: 'span', classes: 'example1' },
			{ title: 'Example 2', inline: 'span', classes: 'example2' },
			{ title: 'Table styles' },
			{ title: 'Table row 1', selector: 'tr', classes: 'tablerow1' }
		],

           // Replace values for the template plugin
           template_replace_values: {
               username: "Some User",
               staffid: "991234"
           }
       });

</script>

FrmBlog/Views/Shared/Footer.cshtml
<div id="footer"> 
		<div id="footer-content"> 	
				
			<div id="footer-bottom">	
				<div class="container clearfix"> 
					<ul id="footer-menu" class="bottom-nav">
                    <li id="menu-item-57" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-57">
     <a href="/">AnaSayfa</a></li> 
<li id="menu-item-50" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-50">
<a href="/">Hakkımızda</a></li> 
<li id="menu-item-89" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89">
<a href="/">iletişim</a></li> 
<li id="menu-item-56" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-56">
<a href="/Home/KullanimSartlari">Kullanım şartları</a></li> 
</ul>											
					<p id="copyright"> Powered by  <a href="http://www.indeksyazilim.com">indeks yazılım</a></p> 
				</div> <!-- end .container -->	
			</div> <!-- end #footer-bottom --> 
		</div> <!-- end #footer-content --> 
	</div> <!-- end #footer --> 
 <script type="text/javascript">
     function initNav() {
         var action = '@ViewContext.RouteData.Values["action"]';
         var controller = '@ViewContext.RouteData.Values["controller"]';
        
         if (action == "Index" && controller == "Home") {
             //             $(".selected_li").attr("class", "");
             $("#nav_li_soru").attr("class", "selected_li");             
         }
         else if (controller == "Etiket") {       
         removeClass();                       
             $("#nav_li_etiket").attr("class", "selected_li");
         } else {
         removeClass();
//             $(".selected_li").attr("class", "");
         }
     }
     initNav();
     function removeClass() {
         $(".tnav > ul > li").each(function (i) {           
             $(this).removeClass("selected_li");
         });
     }
 </script>
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-11329003-4']);
    _gaq.push(['_trackPageview']);

    (function () {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>
   

FrmBlog/Views/Shared/Header.cshtml
@using Microsoft.Web.Mvc; 
@using FrmBlog.Controllers;
<div id="header"> 
		<div id="header-inner"> 
			<div class="container"> 
            <div style="float:left">
				<a href="/">               
 <img src="../../Content/images/logo.png" alt="mayestro.net" id="logo"/>                                                       
				</a> 
				</div>

<div style="float:right;">

<div id="logindisplay">
@Html.Partial("_LogOnPartial")
</div>	
</div>
</div> <!-- end .container --> 
</div> <!-- end #header-inner --> 
</div> <!-- end #header --> 
 <div id="search-bar">	
 <div id="searchinput_wraper">			
<input type="text" value="Ara..." name="s" id="searchinput" onkeyup="Ara(event)" onblur="if(this.value=='') this.value='Ara...';" onfocus="if(this.value=='Ara...') this.value='';" />  
				</div>
			</div> <!-- end #search-bar --> 		
<div class="cbt"></div>
    <div id="tnav-wrapper">
            <div class="tnav">
           
<ul>
<li id="nav_li_soru" class="selected_li">
<a id="nav-questions" href="/">Sorular</a>
</li>
<li>
<a  href="/">En Çok Ziyaret Edilenler</a>
</li>
<li>
<a  href="/">Cevapsızlar</a>
</li>
<li id="nav_li_etiket">
@(Html.ActionLink<EtiketController>(x => x.Etiketler(null, ""), "Etiketler"))
</li>
@*<li>
@Html.ActionLink("Tag", "Index", "Tag", new { area="YonetimPaneli"},null)
</li>*@
</ul>
</div>
 <div class="askquestion">
<ul>
<li>
<a id="nav-askquestion" href="/soru/sor">Soru Sor</a>
</li>
</ul>
</div>
 </div> 

 <div class="cbt"></div>
 <script language="javascript" type="text/javascript">
     function IsNumeric(sText) {
         if (sText == "")
             return false;
         var ValidChars = "0123456789.";
         var IsNumber = true;
         var Char;
         for (i = 0; i < sText.length && IsNumber == true; i++) {
             Char = sText.charAt(i);
             if (ValidChars.indexOf(Char) == -1) {
                 IsNumber = false;
             }
         }
         return IsNumber;
     }
     function Ara(e) {
         var unicode = e.keyCode ? e.keyCode : e.charCode;
         var sea = document.getElementById('searchinput').value;
         if (unicode == 13 && sea != "" && sea != "ara...") {

             var controller = '@ViewContext.RouteData.Values["controller"]';
             var action = '@ViewContext.RouteData.Values["action"]';

             if (controller != 'Ara') {

                 //var url2 = '

                 var url2 = '@Url.Action("Index","Ara")';
                 var querystring2 = "";
                 if (sea != "") {
                     querystring2 = "?q=" + sea;
                 }               
                 document.location.href = url2 + querystring2;
             }
             else {
                 var url = document.location.href.split('?')[0];
                 var str = "";
                 str = url.substring(url.lastIndexOf('/') + 1, url.length);
                 if (IsNumeric(str)) {
                     url = url.substring(0, url.lastIndexOf('/'));
                 }
                 var querystring = "";
                 var first = false;
                 if (sea != "") {
                     first = true;
                     querystring += "q=" + sea;
                 }

                 if (querystring != "")
                     document.location.href = url + '?' + querystring;
                 else
                     document.location.href = url;
             }
         }
     }
 </script>	

    

FrmBlog/Views/Shared/ListeData.cshtml
@model FrmBlog.ViewData.FrmViewData
@using FrmBlog.Repositorys;   
@using Microsoft.Web.Mvc; 
@using FrmBlog.Controllers;  
@using FrmBlog.Helpers;     
@{
    RepositoryAnswers _repoAns = new RepositoryAnswers("", DbType.SqLite);
    RepositoryQuestionVisit _repoIst = new RepositoryQuestionVisit("", DbType.SqLite);
    RepositoryTag _repoTag = new RepositoryTag("", DbType.SqLite);   
}
<div class="clear"></div>	
<div id="question-mini-list">
@{
    if(Model.Questions.Count==0)
    {
        <p>Soru eklenmemiş.</p>
    }
}
@foreach (var q in Model.Questions)
{
 <div class="question-summary first-border" id="@q.QuestionId">
 @{
    string status = "unanswered";
    string title = "";
    int countAns = @_repoAns.AnswerCountOfQuestion(@q.QuestionId);
    bool bestRep = @_repoAns.HaveBestReply(@q.QuestionId);
    if (bestRep)
    {
        status = "answered-accepted";
        title = "cevaplardan biri doğru cevap olarak işaretlemiş.";
    }
    else if (countAns > 0)
    {
        status = "answered";
    }
}
<div onclick="window.location.href='@Url.Action("Detay", "Soru", new { id = @q.QuestionId, title = @Html.Raw(q.Title.ConvertWebUrl()) })'" class="cp">
<div class="status @status" title="@title">
<div class="mini-counts">@countAns</div>
<div>Cevap</div>
</div>
<div class="views">
<div class="mini-counts">@_repoIst.VisitCount(@q.QuestionId)</div>
<div>Ziyaret</div>
</div>
</div>
<div class="summary">
<h3>
@(Html.ActionLink<SoruController>(x => x.Detay(@q.QuestionId, @q.Title.ConvertWebUrl()), @q.Title.Replace("%t%", "'").Replace("@@", "@"), new { @class = "question-hyperlink", title = @Html.Raw(q.Title.Replace("%t%", "'").Replace("@@", "@")) }))
</h3>
<div class="tags2">
@{
    var tags = _repoTag.GetListByQuestionId(@q.QuestionId);
    foreach (var t in tags)
    {
   @(Html.ActionLink<EtiketController>(x => x.Tag(@t.TagName,null), @t.TagName, new { @class = "post-tag", rel = "tag" }))  
    }
}
</div>
<div class="started">
<span title="" class="relativetime">@q.Date.ToLongDateString()</span>
<p>@q.User.Name</p>
</div>
</div>
</div>    
}
</div><!-- question-mini-list -->

FrmBlog/Views/Shared/Yonetim.cshtml
@using FrmBlog.Helpers;
@using Microsoft.Web.Mvc;
@using FrmBlog.Controllers;
@using FrmBlog.Models;
@using System.Security.Principal;
@using FrmBlog.Repositorys;
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
 <script type="text/javascript">
     $(document).ready(function () {
         var controller = '@ViewContext.RouteData.Values["controller"]';
         var action = '@ViewContext.RouteData.Values["action"]';
         //alert(controller+"-"+action);
         var contAct = controller + "/" + action;
         $(".tabs").find("a").each(function () {
             var controllerMatch = $(this).attr("name");

             if (controllerMatch == contAct) {
                 $(this).parent("li").attr("class", "current");
             }
         });
     });
    </script>
</head>
<body>
   <div id="container">	
	<div id="header">
		<span style="float:left"><h1>Site Administration</h1></span>
        <span style="float:right;padding:5px;">
        <a href="/">AnaSayfa</a>
        </span>            
	</div>      
<div class="tabs"> 
<ul>
<li>@Html.ActionLink("","Tag","Etiket") <span>Etiket</span></a></li>
<li><a href="/YonetimPaneli/Page.aspx" name="Page/Index"><span>Sayfa</span></a></li>
<li><a href="/YonetimPaneli/Menu.aspx" name="Menu/Index"><span>Menü</span></a></li>
<li><a href="/YonetimPaneli/Product.aspx" name="Product/Index"><span>Ürün</span></a></li>
<li><a href="/YonetimPaneli/Marka.aspx" name="Marka/Index"><span>Marka</span></a></li>   
<li><a href="/YonetimPaneli/Setting.aspx" name="Setting/Index"><span>Ayarlar</span></a></li>   
<li><a href="/YonetimPaneli/Iletisim.aspx" name="Iletisim/Index"><span>Iletişim</span></a></li> 
<li><a href="/YonetimPaneli/Haber.aspx" name="Haber/Index"><span>Haberler</span></a></li>  
<li><a href="/YonetimPaneli/User.aspx" name="User/Index"><span>Kullanıcı</span></a></li>  
</ul>
    </div>
    <div id="main">
	 	 <span class="success">@ViewData["Success"] == null ? "" : @Html.Encode(ViewData["Success"])</span>
		 <span class="error">@ViewData["Error"] == null ? "" : @Html.Encode(ViewData["Error"])</span>
	    @RenderBody()
    </div>
   @* <div id="footer"><%=Html.SiteName() %></div>*@
</div>
    <div>       
    </div>
    
</body>
</html>

FrmBlog/Views/Shared/_Layout.cshtml
@using FrmBlog.Helpers;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
     <meta name="keywords" content=@Html.MetaKeyboard()  /> 
    <meta name="description" content=@Html.MetaDescription() /> 
    <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1254"> 
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-9"> 
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" >
    <title>@ViewBag.Title</title>
   @*   <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css" />
    <link href="../../Content/jquery.tagit.css" rel="stylesheet" type="text/css" />*@
   <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:light,regular,bold&amp;subset=latin' rel='stylesheet' type='text/css' />
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>

   @* <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="../../Scripts/jquery-1.5.1-vsdoc.js" type="text/javascript"></script>*@
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    @RenderSection("HeadSide",required:false)	
 
</head>
<body id="home"> 
	@Html.Partial("Header")
	
	<div id="content" > 			
	<div class="container clearfix"> 
<div id="main-area"> 	
	<div id="main-recent"> 
@RenderBody()		
</div> <!-- end #main-recent --> 

</div> <!-- end #main-area --> 
	 @RenderSection("SideBar",required:false)	
			</div> <!-- end .container -->	
		
	</div> <!-- end #content --> 
     <div class="cbt">&nbsp;</div>	
@Html.Partial("Footer")			


 
</body> 
</html>

FrmBlog/Views/Shared/_Layout2.cshtml
@using FrmBlog.Helpers;
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title.Replace("%t%", "'").Replace("@@", "@")</title>
     <meta charset="utf-8" />
      <meta name="keywords" content=@Html.MetaKeyboard()  /> 
    <meta name="description" content=@Html.MetaDescription() /> 
    <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1254"> 
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-9"> 
    <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:light,regular,bold&amp;subset=latin' rel='stylesheet' type='text/css' />
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
   
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" >
</head>
<body id="home">
	@Html.Partial("Header")
  
<div class="container">
<div id="content">
 @RenderBody()
</div> <!-- end .container --> 				
</div> <!-- end #content -->
<div class="clear"></div>
 @Html.Partial("Footer")
</body>
</html>

FrmBlog/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated)
{
   <text> 
    <strong>@(((FrmBlog.Models.User)HttpContext.Current.User).Name)</strong>!
    [ @Html.ActionLink("Çıkış", "LogOff", "Account") ]
    </text>
   
}
else
{    
    string rurl = @Request["ReturnUrl"];
    if (string.IsNullOrEmpty(rurl))
    {
        rurl = Request.Url.AbsolutePath; 
    } 
  
   <p>
      [ @Html.ActionLink("Giriş", "LogOn", "Account", new { ReturnUrl=@rurl},null) ]
    [@Html.ActionLink("Üye Ol", "Register", "Account", new { ReturnUrl = @rurl }, null)]
    </p>
  
}

FrmBlog/Views/Shared/_LogonOpenId.cshtml
@model dynamic      
@using DotNetOpenAuth.Mvc;
@using DotNetOpenAuth.OpenId.RelyingParty;
@using Microsoft.Web.Mvc;
<div id="login-oauth">
    <fieldset>
        <legend style="width:350px">Aşağıdaki sitelerin birinden hesap sahibi misiniz? Logoya tıklayıp kayıt olup bağlanın:</legend>
        @using (Html.BeginForm("LogOnPostAssertion", "Auth"))
        {
            @Html.Hidden("ReturnUrl", Request.QueryString["ReturnUrl"], new { id = "ReturnUrl" })
            @Html.Hidden("openid_openidAuthData") 
            <div>
                @MvcHtmlString.Create(Html.OpenIdSelector(new SelectorButton[] {
new SelectorProviderButton("https://me.yahoo.com/", Url.Content("~/Content/images/yahoo.gif")),
new SelectorProviderButton("https://www.google.com/accounts/o8/id", Url.Content("~/Content/images/google.gif")),
new SelectorOpenIdButton(Url.Content("~/Content/images/openid.gif")),
}))
              @*  <div class="helpDoc">
                    <p>
                        If you have logged in previously, click the same button you did last time!!
                    </p>
                </div>*@
            </div>
        }
    </fieldset>
    <div class="cbt">
<p>
Eğer yukarıdaki sitelerden hesap sahibi değilseniz
</p>
<p>
 @Html.ActionLink("Kayıt olmak için tıklayın", "Register", "Account", new {ReturnUrl=@Request["ReturnUrl"] },null)
</p>
 <h6>üye olarak kullanım şartlarını kabul etmiş olursunuz okumak için <a href="/Home/KullanimSartlari">tıklayın</a></h6>
</div>
</div>
@{     
    var options = new OpenIdSelector();
    options.TextBox.LogOnText = "Log On";
}
@MvcHtmlString.Create(Html.OpenIdSelectorScripts(options,null))